setono_sylius_algolia_shop_product_index:
    path: '%setono_sylius_algolia.routes.product_index%'
    methods: [GET]
    controller: setono_sylius_algolia.controller.action.product_index
    requirements:
        slug: .+
