framework:
    cache:
        pools:
            setono_sylius_algolia.cache_pool.recommendations:
                adapter: "%setono_sylius_algolia.cache.adapter%"
    messenger:
        buses:
            setono_sylius_algolia.command_bus: ~
            setono_sylius_algolia.event_bus:
                default_middleware: allow_no_handlers
